Documentation for `findall` method
BioJulia/BioSequences.jl pull request #236
Opened 2022-06-15 15:47 UTC by CiaranOMara

This PR:
- adds a docblock to the `findall` method.
- expands find examples to include `findall` where possible.

2022-08-01 05:52 UTC, jakobnissen requested changes
Thanks, just a few nitpicks

2022-08-01 05:52 UTC, jakobnissen commented on src/BioSequences.jl
> +The `pattern` can be a `Biosymbol` or a predicate.
Or a search query

2022-08-01 05:52 UTC, jakobnissen commented on src/BioSequences.jl
> +julia> seq = dna"ACACACAC"
Maybe suppress output from this line to reduce visual noise (no big thing)

2022-08-01 11:10 UTC, CiaranOMara commented
Those are good nits to get out.

2022-08-02 11:54 UTC, jakobnissen approved these changes

2022-08-02 22:32 UTC, merged